version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: py9-Akc-UWU-P7n
      POSTGRES_USER: dcs_user
    volumes:
      - ./dcs-site-db:/var/lib/postgresql/data